# Generated by Django 4.0.3 on 2022-04-22 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mem', '0002_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='likes',
            field=models.ManyToManyField(related_name='mem_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
